version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: reactive_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 000
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:\dt